### ISSUE TITLE
BlockChypException for timeouts

### ISSUE THREAD

**Issue by intricate** [blockchyp/blockchyp-csharp#14]
Not necessary at all, but it might be nice to have a sort of `BlockChypException` that is thrown when an endpoint such as charge or preauth timeout. Right now you will get an `HttpRequestException` but it feels a bit clunky to have to understand what the `BlockChypClient` is utilizing under-the-hood in order to effectively handle this exception. I imagine that, visually, it'd be a bit more intuitive to catch a sort of `BlockChypException` to handle a timeout.

**Comment by intricate** [comment]
Ah, actually I just thought about this: in the event of organic HTTP timeouts (ones caused by network issues, I mean), it might be weird to catch a `BlockChypException`. 

Maybe timeouts should be documented instead? I'm not entirely sure what the best course of action is.

**Comment by intricate** [comment]
Whoops, I just noticed that you guys do document this kind of thing under https://github.com/blockchyp/blockchyp-csharp#time-out-reversal and also throw a standard exception, `TimeoutException`, in `TerminalRequestAsync` and `GatewayRequestAsync`.

However, I think I never noticed because the timeout properties are set to `Timeout.InfiniteTimeSpan` by default, so a `TimeoutException` was never thrown, but the typical `HttpRequestException` was.

**Comment by jniedrauer** [comment]
I wonder if we should catch the HttpRequestException and rethrow something else anyway. Can you provide steps to reproduce this? I'm assuming it's something like: Leave timeouts set to infinite, send a request to a host that's not on the network, or can't be resolved, or something?

**Comment by intricate** [comment]
Yeah, that's exactly right. Leaving the timeouts set to infinite and sending a request to a host that's not on the network is a good way to reproduce. So perhaps just switch over to a subnet which is different than that which the terminal lives on and try to use the `ChargeAsync` method or something (without utilizing the cloud relay stuff, of course).

**Comment by jniedrauer** [comment]
Set default timeouts and added per-request timeouts.
